# Generated by Django 4.2.4 on 2023-08-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=35)),
                ('code', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('pc_mail', models.EmailField(max_length=254)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option1_count', models.IntegerField(default=0)),
                ('option2_count', models.IntegerField(default=0)),
                ('option3_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('opn', 'Open'), ('cls', 'Close')], default='opn', max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-question'],
                'indexes': [models.Index(fields=['-question'], name='polls_polls_questio_b85e83_idx')],
            },
        ),
    ]
